# .circleci/config.yml
version: 2.1
orbs:
  win: circleci/windows@5.0.0
  
jobs:
  build:
    executor:
      name: win/server-2022
    steps:
      - checkout
      - run:
          command: cd "C:\Users\circleci.PACKER-631B74C9\project\Group 2"
          shell: cmd.exe
      - run:
          command: dir
          shell: cmd.exe
