version: 2.1
jobs:
  build:
    working_directory: ~/project/TLTQ/src
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout:
          path: ~/project
      - run: cd .. && mkdir bin && cd bin && mkdir linux
      - run: make linux-build