# .circleci/config.yml
version: 2.1
orbs:
  win: circleci/windows@5.0.0
  
jobs:
  build:
    working_directory: "~/project/Group 2"
    executor:
      name: win/server-2022
    steps:
      - checkout:
          path: ~/project/ 
      - run:
          command: echo changed
          shell: cmd.exe
      - run:
          command: dir
          shell: cmd.exe
      - run:
          command: MSBuild "Group 2.sln" /t:Build  /p:Platform=x64 /p:Configuration=Release
          shell: cmd.exe
