# .circleci/config.yml
version: 2.1
orbs:
  win: circleci/windows@5.0.0
  
jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
          command: echo $CIRCLE_WORKING_DIRECTORY
          shell: cmd.exe
      - run:
          command: dir .
          shell: cmd.exe
