# .circleci/config.yml
version: 2.1
orbs:
  win: circleci/windows@5.0.0
  
jobs:
  build:
    executor:
      name: win/server-2022
    steps:
      - checkout 
      - run:
          working_directory: "~/project/Group 2"
          command: echo ${working_directory}
          shell: cmd.exe
      - run:
          command: dir
          shell: cmd.exe
