# .circleci/config.yml
version: 2.1
  
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      # Whatever you want to do
      - run: apt-cache search sfml
      #- run: sudo apt-get install libsfml-dev
      - run: apt list --installed
