# .circleci/config.yml
version: 2.1
orbs:
  msix: circleci/microsoft-msix@1.1.1
  win: circleci/windows@5.0.0
jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
          command: CD "C:\Program Files C:\Program Files\Microsoft Visual Studio\2022\Community\Msbuild\Current\Bin"
          shell: cmd.exe
