version: 2.1
orbs: 
   win: circleci/windows@5.0
jobs:
  build-linux:
    working_directory: ~/project/TLTQ/src
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout:
          path: ~/project
      #- run: sudo apt-get install libsfml-dev
      #- run: cd .. && mkdir bin && cd bin && mkdir linux
      - run: make linux-compile
  build-windows:
    working_directory: ~/project/TLTQ/src
    executor: win/default
    steps:
      - checkout:
          path: ~/project
      - run: choco install make -y
      - run: choco install mingw -y
      - run: make windows-build
  cppcheck:
    working_directory: ~/project/TLTQ/src
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout:
          path: ~/project
      - run: sudo apt install cppcheck
      - run: cppcheck --enable=all --error-exitcode=1 .
workflows:
    linux:
        jobs:
            - build-linux
            - cppcheck
    windows:
      jobs:
        - build-windows