version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      #- checkout
      - run: sudo apt clean
      - run: sudo apt autoclean
      - run: sudo apt update
      - run: sudo apt-get install libsfml-dev
      - run: app list --installed