# .circleci/config.yml
version: 2.1

orbs:
  # We pin the minor version but leave out the patch version
  # to automatically accept non-breaking improvements.
  msix: circleci/microsoft-msix@1.1.1
  # Gives us easy access to Windows execution environments.
  win: circleci/windows@5.0.0

working-dir: ~/project/Group 2
    
jobs:
  using-sln:
    executor:
      name: win/server-2019
    steps:
      - checkout
      - msix/pack

workflows:
  demo:
    jobs:
      - using-sln
      
