# .circleci/config.yml
version: 2.1
orbs:
  msix: circleci/microsoft-msix@1.1.1
  win: circleci/windows@5.0.0
jobs:
  using-sln:
    executor:
      name: win/server-2019
    steps:
      - checkout
      - msix/pack:
          import-cert: true
          parameters: '/p:Platform=x64 /p:Configuration=Release'
          working-dir: '~/project/Group 2'
          #sdk-version: '10.0.22621'
workflows:
  build:
    jobs:
      - using-sln