version: 2.1
orbs: 
   win: circleci/windows@5.0
jobs:
  build-linux:
    working_directory: ~/project/TLTQ/src
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout:
          path: ~/project
      #- run: sudo apt-get install libsfml-dev
      #- run: cd .. && mkdir bin && cd bin && mkdir linux
      - run: make linux-compile
  
  build-windows:
    working_directory: ~/project/TLTQ/src
    executor: win/default
    steps:
      - checkout:
          path: ~/project
      - run: choco install make -y
      - run: choco install mingw -y
      - run: choco install 7zip.install -y
      - run: make windows-build
      - run:
          name: delete gitkeep
          command: |
            cd ..
            cd bin/win
            del gitkeep
            cd ..
            7z a -tzip out.zip win 

      - store_artifacts:
          path: ~/project/TLTQ/bin/out.zip
          destination: artifact-file
  
  cppcheck:
    working_directory: ~/project/TLTQ/src
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout:
          path: ~/project
      - run: sudo apt install cppcheck
      - run: cppcheck --enable=all --error-exitcode=1 .

workflows:
    linux:
        jobs:
            - build-linux
            - cppcheck
    windows:
      jobs:
        - build-windows